
CREATE OR REPLACE VIEW public.swing_ml_training_dataset_v1
WITH (security_invoker = true) AS
SELECT
  e.id,
  e.user_id,
  e.ticker,
  e.company,
  e.checked_at,
  e.checked_date_et,
  e.was_selected,
  e.status_at_check,
  e.best_window,
  e.selected_window,
  e.current_price,
  e.market_cap,
  e.analyst_signal,
  e.one_session_return_pct,
  e.seven_session_return_pct,
  e.twenty_session_return_pct,
  e.volume_strength,
  e.risk_reward,
  e.technical_score,
  e.volatility_score,
  e.distance_from_support_pct,
  e.distance_to_resistance_pct,
  e.overbought_flag,
  e.weak_volume_flag,
  e.high_volatility_flag,
  e.near_resistance_flag,
  e.extended_flag,
  e.exa_positive_signal_count,
  e.exa_negative_signal_count,
  e.exa_neutral_signal_count,
  e.exa_source_quality_score,
  e.has_revenue_growth_signal,
  e.has_raised_outlook_signal,
  e.has_earnings_beat_signal,
  e.has_analyst_upgrade_signal,
  e.has_price_target_raise_signal,
  e.has_fda_approval_signal,
  e.has_contract_win_signal,
  e.has_partnership_signal,
  e.has_lawsuit_signal,
  e.has_material_lawsuit_signal,
  e.has_generic_lawsuit_noise,
  e.has_investigation_signal,
  e.has_downgrade_signal,
  e.has_earnings_miss_signal,
  e.has_guidance_cut_signal,
  e.has_high_valuation_signal,
  e.has_insider_selling_signal,
  e.has_cash_burn_signal,
  e.has_margin_pressure_signal,
  e.finnhub_available,
  e.sector,
  e.industry,
  e.peer_count,
  e.peer_confirmation_score,
  e.analyst_buy_count,
  e.analyst_hold_count,
  e.analyst_sell_count,
  e.analyst_score,
  e.target_mean,
  e.target_upside_pct,
  e.target_supports_trade,
  e.rule_based_final_score,
  e.confidence,
  e.rejection_reason,
  e.learning_bonus,
  e.learning_penalty,
  e.final_swing_score,
  o.sessions_elapsed,
  o.price_at_check,
  o.current_price AS outcome_current_price,
  o.max_high_since_check,
  o.min_low_since_check,
  o.return_pct_current,
  o.max_gain_pct,
  o.max_drawdown_pct,
  o.target_hit,
  o.stop_hit,
  o.label_3_session,
  o.label_10_session,
  o.label_20_session,
  o.label_40_session,
  o.final_label
FROM public.swing_training_examples e
LEFT JOIN public.swing_training_outcomes o
  ON o.training_example_id = e.id;

GRANT SELECT ON public.swing_ml_training_dataset_v1 TO authenticated;
GRANT SELECT ON public.swing_ml_training_dataset_v1 TO service_role;
